language: scala
sudo: false
jdk:
- oraclejdk8

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - env: TEST="docs"
      script: sbt tut
    - env: TEST="test"
      script: sbt +test
    - env: TEST="coverage"
      script: sbt coverage test && sbt coverageReport && bash <(curl -s https://codecov.io/bash)
    - stage: release
      script: sbt ci-release

# These directories are cached to S3 at the end of the build
cache:
directories:
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
